### ISSUE TITLE
invalid package name fix/oz1140: the name contains unexpected character

### ISSUE THREAD

**Issue by sdaf47** [b2broker/simplefix-go#22]
```
$ fixgen -o="./fix/oz1140" -s=fix.4.4.onezero.taker.1.14.0.xml -t=types.xml
panic: invalid package name fix/oz1140: the name contains unexpected character

goroutine 1 [running]:
main.main()
        /Users/sbulatkin/go/src/github.com/b2broker/simplefix-go/cmd/fixgen/main.go:40 +0x4cd
sbulatkin@AirSBulatkin source % fixgen -o="./oz1140" -s=fix.4.4.onezero.taker.1.14.0.xml -t=types
```

**Comment by liqlvnvn** [comment]
This issue has been migrated to our internal Jira as part of the GitHub → GitLab library migration (B2CT-19464): https://b2broker.atlassian.net/browse/B2CT-19481

**Comment by liqlvnvn** [comment]
Fixed in v1.18.0 on the canonical GitLab mirror (gitlab.b2broker.tech/highload/b2connect/libs/go/simplefix-go).

`generator/generator.go:116` calls `g.checkName(pkg)` before any codegen. `checkName` (:45-59) rejects names matching `[^a-z0-9_]+` (which covers `/`) and returns a wrapped error — no panic. The fix landed with the module-path rename in tag `v1.18.0`.

Closing as **Fixed**. Tracked in Jira as B2CT-19481.
